/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly NODE_ENV: string
  readonly VITE_TRPC_URL: string
  readonly SENTRY_AUTH_TOKEN: string
  readonly SENTRY_DSN: string
  readonly SENTRY_ORG: string
  readonly SENTRY_PROJECT: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}